In [1]:
import pandas as pd

In [3]:
df =  pd.read_csv(r"D:\HP\Downloads\recipes (1).csv")

In [4]:
df.head(3)

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src
0,0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,"3 tablespoons butter, 2 pounds Granny Smith ap...",Heat butter in a large skillet over medium-hig...,4.4,https://www.allrecipes.com/recipe/76931/apple-...,/Desserts/Fruit Desserts/Apple Dessert Recipes/,"Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...","Servings: 8, Yield: 6 to 8 - servings",https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,"8 small Granny Smith apples, or as needed, ½ c...","Peel and core apples, then thinly slice. Set a...",4.8,https://www.allrecipes.com/recipe/12682/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...","Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...",https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,"4 apples - peeled, cored and chopped, ¾ cup w...","Combine apples, water, sugar, and cinnamon in ...",4.8,https://www.allrecipes.com/recipe/51301/sarahs...,/Side Dish/Applesauce Recipes/,"Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...","Prep Time: 10 mins, Cook Time: 15 mins, Total ...",https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...

In [5]:
df.shape

(1090, 15)

In [6]:
df.columns

Index(['Unnamed: 0', 'recipe_name', 'prep_time', 'cook_time', 'total_time',
       'servings', 'yield', 'ingredients', 'directions', 'rating', 'url',
       'cuisine_path', 'nutrition', 'timing', 'img_src'],
      dtype='str')

In [7]:
df.info

<bound method DataFrame.info of       Unnamed: 0                        recipe_name prep_time cook_time  \
0              0           Apple-Cranberry Crostada       NaN       NaN
1              1          Apple Pie by Grandma Ople   30 mins     1 hrs
2              2        Sarah's Homemade Applesauce   10 mins   15 mins
3              3                        Apple Crisp   30 mins   45 mins
4              4                  Apple Pie Filling   20 mins   20 mins
...          ...                                ...       ...       ...
1085        1085                     Date-Nut Balls   15 mins   10 mins
1086        1086                       Jamaica Cake       NaN       NaN
1087        1087                     Best Hot Sauce   10 mins   20 mins
1088        1088               Moist Date Nut Bread   15 mins   50 mins
1089        1089  Chef John's Chocolate Energy Bars   15 mins       NaN

         total_time  servings              yield  \
0               NaN         8  6 to 8 - servings
1     1 hrs 30 mins         8       1 9-inch pie
2           25 mins         4                NaN
3     1 hrs 15 mins        12    1 9x13-inch pan
4     2 hrs 40 mins        40      5 9-inch pies
...             ...       ...                ...
1085        30 mins        48      4 dozen balls
1086            NaN        14  1 - 13x9 inch pan
1087        30 mins       100             2 cups
1088  1 hrs 35 mins        12    1 9x5-inch loaf
1089          3 hrs        12            12 bars

                                            ingredients  \
0     3 tablespoons butter, 2 pounds Granny Smith ap...
1     8 small Granny Smith apples, or as needed, ½ c...
2     4  apples - peeled, cored and chopped, ¾ cup w...
3     10 cups all-purpose apples, peeled, cored and ...
4     18 cups thinly sliced apples, 3 tablespoons le...
...                                                 ...
1085  14 tablespoons butter, 1 cup pitted chopped da...
1086  2 cups white sugar, 1 ½ cups vegetable oil, 1 ...
1087  10  fresh hot chile peppers, stems removed, 1 ...
1088  2 ½ cups chopped dates, ¼ cup butter, 1 cup bo...
1089  2 cups pitted Medjool dates, roughly chopped, ...

                                             directions  rating  \
0     Heat butter in a large skillet over medium-hig...     4.4
1     Peel and core apples, then thinly slice. Set a...     4.8
2     Combine apples, water, sugar, and cinnamon in ...     4.8
3     Preheat the oven to 350 degrees F (175 degrees...     4.7
4     Toss apples with lemon juice in a large bowl a...     4.7
...                                                 ...     ...
1085  Melt butter in a saucepan over medium heat; co...     3.8
1086  Mix together sugar, vegetable oil, pecans, flo...     4.6
1087  Place peppers, onion, dates, basil, parsley, t...     4.9
1088  Preheat the oven to 350 degrees F (175 degrees...     4.5
1089  Place cashews, almonds, coconut, dates, cocoa,...     4.8

                                                    url  \
0     https://www.allrecipes.com/recipe/76931/apple-...
1     https://www.allrecipes.com/recipe/12682/apple-...
2     https://www.allrecipes.com/recipe/51301/sarahs...
3     https://www.allrecipes.com/recipe/12409/apple-...
4     https://www.allrecipes.com/recipe/12681/apple-...
...                                                 ...
1085  https://www.allrecipes.com/recipe/240653/date-...
1086  https://www.allrecipes.com/recipe/7509/jamaica...
1087  https://www.allrecipes.com/recipe/242153/best-...
1088  https://www.allrecipes.com/recipe/51446/moist-...
1089  https://www.allrecipes.com/recipe/254452/chef-...

                                           cuisine_path  \
0       /Desserts/Fruit Desserts/Apple Dessert Recipes/
1                     /Desserts/Pies/Apple Pie Recipes/
2                        /Side Dish/Applesauce Recipes/
3     /Desserts/Crisps and Crumbles Recipes/Apple Cr...
4                     /Desserts/Pies/Apple Pie Recipes/
...                                                 ...
1085       /Desserts/Cookies/Fruit Cookie Recipes/Date/
1086   /Desserts/Fruit Desserts/Banana Dessert Recipes/
1087                  /Side Dish/Sauces and Condiments/
1088     /Breakfast and Brunch/Breakfast Bread Recipes/
1089  /Appetizers and Snacks/Snacks/Granola Bar Reci...

                                              nutrition  \
0     Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...
1     Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...
2     Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...
3     Total Fat 8g 11%, Saturated Fat 5g 25%, Choles...
4     Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohy...
...                                                 ...
1085  Total Fat 5g 6%, Saturated Fat 2g 12%, Cholest...
1086  Total Fat 33g 43%, Saturated Fat 4g 21%, Chole...
1087  Total Fat 1g 1%, Saturated Fat 0g 1%, Sodium 2...
1088  Total Fat 10g 13%, Saturated Fat 3g 16%, Chole...
1089  Total Fat 22g 28%, Saturated Fat 7g 36%, Sodiu...

                                                 timing  \
0                 Servings: 8, Yield: 6 to 8 - servings
1     Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...
2     Prep Time: 10 mins, Cook Time: 15 mins, Total ...
3     Prep Time: 30 mins, Cook Time: 45 mins, Total ...
4     Prep Time: 20 mins, Cook Time: 20 mins, Additi...
...                                                 ...
1085  Prep Time: 15 mins, Cook Time: 10 mins, Additi...
1086             Servings: 14, Yield: 1 - 13x9 inch pan
1087  Prep Time: 10 mins, Cook Time: 20 mins, Total ...
1088  Prep Time: 15 mins, Cook Time: 50 mins, Additi...
1089  Prep Time: 15 mins, Additional Time: 2 hrs 45 ...

                                                img_src
0     https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1     https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2     https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3     https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4     https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...
...                                                 ...
1085  https://www.allrecipes.com/thmb/LXm_15zLymhZ7c...
1086  https://www.allrecipes.com/thmb/tI7g5xY5-qPV5v...
1087  https://www.allrecipes.com/thmb/80wUYzFvbycfxx...
1088  https://www.allrecipes.com/thmb/bYsnompJZ6UAF9...
1089  https://www.allrecipes.com/thmb/IOoj42MMo8YNKW...

[1090 rows x 15 columns]>

In [8]:
df['recipe_name'].unique

<bound method Series.unique of 0                Apple-Cranberry Crostada
1               Apple Pie by Grandma Ople
2             Sarah's Homemade Applesauce
3                             Apple Crisp
4                       Apple Pie Filling
                      ...
1085                       Date-Nut Balls
1086                         Jamaica Cake
1087                       Best Hot Sauce
1088                 Moist Date Nut Bread
1089    Chef John's Chocolate Energy Bars
Name: recipe_name, Length: 1090, dtype: str>

In [9]:
df.describe()

        Unnamed: 0     servings       rating
count  1090.000000  1090.000000  1090.000000
mean    544.500000    13.755046     4.533853
std     314.800201    19.886076     0.349814
min       0.000000     1.000000     2.000000
25%     272.250000     6.000000     4.400000
50%     544.500000     8.000000     4.600000
75%     816.750000    12.000000     4.700000
max    1089.000000   240.000000     5.000000

In [10]:
recipe_data = df[['recipe_name','rating','prep_time']]
recipe_data

                            recipe_name  rating prep_time
0              Apple-Cranberry Crostada     4.4       NaN
1             Apple Pie by Grandma Ople     4.8   30 mins
2           Sarah's Homemade Applesauce     4.8   10 mins
3                           Apple Crisp     4.7   30 mins
4                     Apple Pie Filling     4.7   20 mins
...                                 ...     ...       ...
1085                     Date-Nut Balls     3.8   15 mins
1086                       Jamaica Cake     4.6       NaN
1087                     Best Hot Sauce     4.9   10 mins
1088               Moist Date Nut Bread     4.5   15 mins
1089  Chef John's Chocolate Energy Bars     4.8   15 mins

[1090 rows x 3 columns]

In [11]:
recipe_data.head()

                   recipe_name  rating prep_time
0     Apple-Cranberry Crostada     4.4       NaN
1    Apple Pie by Grandma Ople     4.8   30 mins
2  Sarah's Homemade Applesauce     4.8   10 mins
3                  Apple Crisp     4.7   30 mins
4            Apple Pie Filling     4.7   20 mins

In [12]:
recipe_rating= df['rating']
recipe_rating

0       4.4
1       4.8
2       4.8
3       4.7
4       4.7
       ...
1085    3.8
1086    4.6
1087    4.9
1088    4.5
1089    4.8
Name: rating, Length: 1090, dtype: float64

In [13]:
recipe_rating.head()

0    4.4
1    4.8
2    4.8
3    4.7
4    4.7
Name: rating, dtype: float64

In [14]:
recipes = df['recipe_name']
recipes

0                Apple-Cranberry Crostada
1               Apple Pie by Grandma Ople
2             Sarah's Homemade Applesauce
3                             Apple Crisp
4                       Apple Pie Filling
                      ...
1085                       Date-Nut Balls
1086                         Jamaica Cake
1087                       Best Hot Sauce
1088                 Moist Date Nut Bread
1089    Chef John's Chocolate Energy Bars
Name: recipe_name, Length: 1090, dtype: str

In [16]:
#recipe ka dataframe
recipes =df['recipe_name']

In [ ]:
#rating ki series
rating_series = pd.Series(recipe_rating)
rating_

In [ ]:
#recipe name or serving ke 5 records

In [15]:
#dataset ke rows andd columns
df

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src
0,0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,"3 tablespoons butter, 2 pounds Granny Smith ap...",Heat butter in a large skillet over medium-hig...,4.4,https://www.allrecipes.com/recipe/76931/apple-...,/Desserts/Fruit Desserts/Apple Dessert Recipes/,"Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...","Servings: 8, Yield: 6 to 8 - servings",https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,"8 small Granny Smith apples, or as needed, ½ c...","Peel and core apples, then thinly slice. Set a...",4.8,https://www.allrecipes.com/recipe/12682/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...","Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...",https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,"4 apples - peeled, cored and chopped, ¾ cup w...","Combine apples, water, sugar, and cinnamon in ...",4.8,https://www.allrecipes.com/recipe/51301/sarahs...,/Side Dish/Applesauce Recipes/,"Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...","Prep Time: 10 mins, Cook Time: 15 mins, Total ...",https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3,3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,"10 cups all-purpose apples, peeled, cored and ...",Preheat the oven to 350 degrees F (175 degrees...,4.7,https://www.allrecipes.com/recipe/12409/apple-...,/Desserts/Crisps and Crumbles Recipes/Apple Cr...,"Total Fat 8g 11%, Saturated Fat 5g 25%, Choles...","Prep Time: 30 mins, Cook Time: 45 mins, Total ...",https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4,4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,"18 cups thinly sliced apples, 3 tablespoons le...",Toss apples with lemon juice in a large bowl a...,4.7,https://www.allrecipes.com/recipe/12681/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohy...","Prep Time: 20 mins, Cook Time: 20 mins, Additi...",https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,1085,Date-Nut Balls,15 mins,10 mins,30 mins,48,4 dozen balls,"14 tablespoons butter, 1 cup pitted chopped da...",Melt butter in a saucepan over medium heat; co...,3.8,https://www.allrecipes.com/recipe/240653/date-...,/Desserts/Cookies/Fruit Cookie Recipes/Date/,"Total Fat 5g 6%, Saturated Fat 2g 12%, Cholest...","Prep Time: 15 mins, Cook Time: 10 mins, Additi...",https://www.allrecipes.com/thmb/LXm_15zLymhZ7c...
1086,1086,Jamaica Cake,NaN,NaN,NaN,14,1 - 13x9 inch pan,"2 cups white sugar, 1 ½ cups vegetable oil, 1 ...","Mix together sugar, vegetable oil, pecans, flo...",4.6,https://www.allrecipes.com/recipe/7509/jamaica...,/Desserts/Fruit Desserts/Banana Dessert Recipes/,"Total Fat 33g 43%, Saturated Fat 4g 21%, Chole...","Servings: 14, Yield: 1 - 13x9 inch pan",https://www.allrecipes.com/thmb/tI7g5xY5-qPV5v...
1087,1087,Best Hot Sauce,10 mins,20 mins,30 mins,100,2 cups,"10 fresh hot chile peppers, stems removed, 1 ...","Place peppers, onion, dates, basil, parsley, t...",4.9,https://www.allrecipes.com/recipe/242153/best-...,/Side Dish/Sauces and Condiments/,"Total Fat 1g 1%, Saturated Fat 0g 1%, Sodium 2...","Prep Time: 10 mins, Cook Time: 20 mins, Total ...",https://www.allrecipes.com/thmb/80wUYzFvbycfxx...
1088,1088,Moist Date Nut Bread,15 mins,50 mins,1 hrs 35 mins,12,1 9x5-inch loaf,"2 ½ cups chopped dates, ¼ cup butter, 1 cup bo...",Preheat the oven to 350 degrees F (175 degrees...,4.5,https://www.allrecipes.com/recipe/51446/moist-...,/Breakfast and Brunch/Breakfast Bread Recipes/,"Total Fat 10g 13%, Saturated Fat 3g 16%, Chole...","Prep Time: 15 mins, Cook Time: 50 mins, Additi...",https://www.allrecipes.com/thmb/bYsnompJZ6UAF9...
1089,1089,Chef John's Chocolate Energy Bars,15 mins,NaN,3 hrs,12,12 bars,"2 cups pitted Medjool dates, roughly chopped, ...","Place cashews, almonds, coconut, dates, cocoa,...",4.8,https://www.allrecipes.com/recipe/254452/chef-...,/Appetizers and Snacks/Snacks/Granola Bar Reci...,"Total Fat 22g 28%, Saturated Fat 7g 36%, Sodiu...","Prep Time: 15 mins, Additional Time: 2 hrs 45 ...",https://www.allrecipes.com/thmb/IOoj42MMo8YNKW...